server:
  port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://eurekaser.cfapps.io/eureka/       
      
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekaser.cfapps.io/eureka/
